services:
  xgc.form_extension.carbon:
    class: Xgc\CarbonBundle\Form\Extension\CarbonTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }
